
using System.Collections;

namespace Evo
{
    public enum EnumError
    {
        ERROR_NOT_FOUND_MAIN_CANVAS,
        ERROR_NOT_VALID_IN_MESSAGE_FOUND,
        ERROR_NOT_VALID_OUT_MESSAGE_FOUND,
        ERROR_NOT_VALID_IN_MESSAGE,
        ERROR_NOT_VALID_OUT_MESSAGE,
        ERROR_NOT_VALID_PROPERTY,
        ERROR_NOT_VALID_MAP_KEY,
        ERROR_NOT_VALID_EOBJECT,
        ERROR_NOT_VALID_UNITY_OBJECT,
        ERROR_NOT_VALID_OBJECT,
        ERROR_NOT_VALID_EOBJECT_ID,
        ERROR_NOT_VALID_EOBJECT_TIME,
        ERROR_NOT_VALID_ECLASS,
        ERROR_NOT_VALID_EMESSAGE,
        ERROR_NOT_VALID_EMESSAGE_MESSAGE,
        ERROR_NOT_VALID_TYPE,
        ERROR_NOT_VALID_MAP,
        ERROR_NOT_FOUND_EMESSAGE_PARAMETER_TYPE,
        ERROR_NOT_VALID_EVENT,
        ERROR_NOT_VALID_EVENT_PARENT,
        ERROR_NOT_VALID_RESOURCE,
        ERROR_NOT_VALID_GPPROPERTY,
        ERROR_NOT_VALID_GOBJECT,
        ERROR_NOT_FIND_ESERVER,
        ERROR_NOT_FIND_ECLIENT,
        ERROR_PINNING_NOT_VALID_ID_ESERVER_REMOTE,
        ERROR_PINNING_NOT_VALID_RSA_ESERVER_REMOTE,
        TYPE_ALERT_DEBUG,
        TYPE_ALERT_WARNING,
        TYPE_ALERT_ERROR,
        TYPE_ALERT_SUCCESS,
    }
}