// ***************************************************************
//
// Evo Framework 
//
// doc:     https://evoframework.github.io
//
// licence: Attribution-NonCommercial-ShareAlike 4.0 International
//
//****************************************************************

using System;
using Evo;

/// <summary>
/// #EOBJECT_SUMMARY#
/// </summary>
[System.Serializable]
public class EObjectTest : EObject
{
    public int propertyInt;
    public float propertyFloat;
    public string propertyString;
    public Map propertyMap;
    public long propertyLong;
    public char propertyChar;
    public byte[] propertyByteArray;
    public bool propertBool;
    public double propertyDouble;

    #region IBinary
    /// <summary>
    /// AutoGenerated EvoGraph #EVOGRAPH_VERSION#
    /// </summary>
    override public void ToStream(System.IO.Stream stream)
    {
        base.ToStream(stream);
        this.DoWrite(propertyInt, stream);
        this.DoWrite(propertyFloat, stream);
        this.DoWrite(propertyString, stream);
        //this.DoWrite(propertyMap, stream);
        this.DoWrite(propertyLong, stream);
        this.DoWrite(propertyChar, stream);
        this.DoWrite(propertyByteArray, stream);
        this.DoWrite(propertBool, stream);
        this.DoWrite(propertyDouble, stream);
    }

    /// <summary>
    /// AutoGenerated EvoGraph #EVOGRAPH_VERSION#
    /// </summary>
    override public void FromStream(System.IO.Stream stream)
    {
        base.FromStream(stream);
        this.propertyInt = this.DoReadInt(stream);
        this.propertyFloat = this.DoReadFloat(stream);
        this.propertyString = this.DoReadString(stream);
        //this.propertyMap = this.DoReadMap(stream);
        this.propertyLong = this.DoReadLong(stream);
        this.propertyChar = this.DoReadChar(stream);
        this.propertyByteArray = this.DoReadByteArray(stream);
        this.propertBool = this.DoReadBool(stream);
        this.propertyDouble = this.DoReadDouble(stream);

    }
    #endregion
}